services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: exam58-php
    networks:
      - laravel

  nginx:
    image: jguyomard/laravel-nginx:1.13
    container_name: exam58-nginx
    volumes:
      - ./volume/web:/var/www/html
      - ./laravel-container/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
    ports:
        - 8080:80

  mysql:
    image: mysql:5.7
    container_name: exam58-mysql5.7
    restart: always
    volumes:
        #- ./volume/sql:/var/lib/mysql
        - my-mysql-volume:/var/lib/mysql
        - ./laravel-container/mysql/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql # 掛載初始化腳本
    environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=mysql"
        - "MYSQL_USER=homestead"
        - "MYSQL_PASSWORD=secret"
    networks:
      - laravel

  sql-admin:
    image: phpmyadmin/phpmyadmin
    container_name: exam58-phpmyadmin
    restart: always
    ports:
        - 8888:80
    environment:
        PMA_HOST: mysql  # 指向 MySQL 容器的服務名稱
        UPLOAD_LIMIT: 100000000
        # - PMA_ARBITRARY: 1
    networks:
      - laravel

  # app
  # quasar-app:
  #   image: tevun/quasar:latest
  #   container_name: quasar-app
  #   user: node
  #   working_dir: /var/www/app
  #   command: bash /var/www/app/docker-compose.sh
  #   volumes:
  #     - ./volume/frontend:/var/www/app
  #     - ./.bin:/home/node/bin
  #   ports:
  #     - 8000:8000
  quasar-app:
    build:
      context: .
      dockerfile: Dockerfile.quasar
    container_name: quasar-app
    ports:
      - 80:8080
    networks:
      - laravel

volumes:
    my-mysql-volume:

networks:
  laravel: